/**
 * Regenerates .design-sync/icons/{fal,far,fas,fab}.ts — curated FontAwesome
 * packs for the design-sync bundle. See NOTES.md for why these exist.
 *
 * Run from the desktop/ repo root:  node .design-sync/gen-icons.mjs
 */
import fs from 'fs'
import path from 'path'
import { createRequire } from 'module'
const require = createRequire(import.meta.url)

const SRC = 'frontend/src'
const files = []
const walk = d => { for (const e of fs.readdirSync(d, { withFileTypes: true })) {
  const p = path.join(d, e.name)
  if (e.isDirectory()) walk(p); else if (/\.(tsx|ts)$/.test(e.name)) files.push(p) } }
walk(SRC)
walk('common/src')   // shared platform/application tables also name icons

// Harvest EVERY kebab/word string literal in the app source, then keep only the
// ones that resolve to a real Font Awesome icon file (the existence check below
// does the filtering).
//
// Deliberately broad. Earlier versions matched only JSX-attribute forms
// (name="x", icon="x"), which silently missed icons the source reaches by
// assignment (`name = 'windows'`), by rewrite (`if (name === 'share') name =
// 'arrow-up-from-bracket'`), or through a lookup table. Every miss renders as a
// correctly-sized but EMPTY hit target — no glyph, no console error, nothing the
// render check can flag. Over-harvesting costs nothing: a string that isn't an
// icon simply has no file and is dropped.
const found = new Set()
for (const f of files) {
  const s = fs.readFileSync(f, 'utf8')
  for (const m of s.matchAll(/['"]([a-z0-9]+(?:-[a-z0-9]+)*)['"]/g)) found.add(m[1])
}

// Common UI icons a design agent reaches for even if the product doesn't yet.
const extra = ['check','xmark','plus','minus','pen','trash','copy','link','gear','user','users','lock',
 'unlock','eye','eye-slash','magnifying-glass','filter','download','upload','rotate','arrow-up','arrow-down',
 'chevron-up','chevron-down','chevron-left','chevron-right','ellipsis','ellipsis-vertical','circle-info',
 'circle-check','circle-exclamation','circle-xmark','triangle-exclamation','star','heart','clock','calendar',
 'folder','file','image','envelope','phone','globe','house','server','database','cloud','wifi','signal',
 'play','pause','stop','forward','backward','bars','grid','list','table','sliders','share-nodes','bookmark',
 'tag','tags','bell','comment','paper-plane','arrow-right-from-bracket','right-to-bracket','shield','key','code',
 'terminal','laptop','desktop','mobile','tablet','print','qrcode','sitemap','network-wired','route','plug']

// Icon.tsx REWRITES some names before handing them to Font Awesome, e.g.
//   if (name === 'share') { name = 'arrow-up-from-bracket' }
// The harvest above only sees the call-site name ('share'), never the rewrite
// target — so the target never gets registered and the icon renders as an
// empty, correctly-sized hit target with no glyph and no error. Parse the
// rewrite pairs straight out of the source so this can't drift.
const iconSrc = fs.readFileSync(`${SRC}/components/Icon.tsx`, 'utf8')
const rewrites = [...iconSrc.matchAll(/name\s*===\s*'([a-z0-9-]+)'\s*\)\s*\{\s*name\s*=\s*'([a-z0-9-]+)'/g)]
for (const [, from, to] of rewrites) found.add(to)
if (rewrites.length) console.log('icon rewrites picked up:', rewrites.map(r => `${r[1]}→${r[2]}`).join(', '))

const all = [...new Set([...found, ...extra])].sort()
const camel = k => 'fa' + k.split('-').map(p => p[0].toUpperCase() + p.slice(1)).join('')

const packs = {
  fal: '@fortawesome/pro-light-svg-icons',
  far: '@fortawesome/pro-regular-svg-icons',
  fas: '@fortawesome/pro-solid-svg-icons',
  fab: '@fortawesome/free-brands-svg-icons',
}

const summary = {}
for (const [pack, pkg] of Object.entries(packs)) {
  const entries = []
  for (const fileId of [...new Set(all.map(camel))]) {
    const file = `node_modules/${pkg}/${fileId}.js`
    if (!fs.existsSync(file)) continue
    // The export name is NOT always the filename: free-brands ships
    // faRaspberrypi.js exporting faRaspberryPi. Read the real name — a
    // mismatch yields `undefined` in the pack and library.add() throws
    // "Cannot read properties of undefined (reading 'prefix')".
    const mod = require(path.resolve(file))
    const exportName = Object.keys(mod).find(k => /^fa[A-Z0-9]/.test(k) && mod[k] && mod[k].prefix)
    if (!exportName) continue
    entries.push({ fileId, exportName })
  }
  summary[pack] = entries.length
  const body = [
    `/* GENERATED by .design-sync/gen-icons.mjs — do not edit by hand.`,
    ` *`,
    ` * Registers only the icons this product actually uses (scraped from`,
    ` * frontend/src) plus a common-UI set, instead of the whole ${pkg}`,
    ` * pack. The three Pro packs are ~45 MB each; bundling them whole made`,
    ` * _ds_bundle.js 15.9 MB, past the 12 MB upload limit.`,
    ` */`,
    ...entries.map(e => `import { ${e.exportName} } from '${pkg}/${e.fileId}'`),
    ``,
    `export const ${pack} = { ${entries.map(e => e.exportName).join(', ')} }`,
    `export default { ${pack} }`,
  ].join('\n')
  fs.writeFileSync(`.design-sync/icons/${pack}.ts`, body + '\n')
}
console.log('icon names requested:', all.length)
console.log('resolved per pack:', JSON.stringify(summary))
