/* GENERATED by .design-sync/gen-icons.mjs — do not edit by hand.
 *
 * Registers only the icons this product actually uses (scraped from
 * frontend/src) plus a common-UI set, instead of the whole @fortawesome/free-brands-svg-icons
 * pack. The three Pro packs are ~45 MB each; bundling them whole made
 * _ds_bundle.js 15.9 MB, past the 12 MB upload limit.
 */
import { faAndroid } from '@fortawesome/free-brands-svg-icons/faAndroid'
import { faApple } from '@fortawesome/free-brands-svg-icons/faApple'
import { faAws } from '@fortawesome/free-brands-svg-icons/faAws'
import { faBluetooth } from '@fortawesome/free-brands-svg-icons/faBluetooth'
import { faBluetoothB } from '@fortawesome/free-brands-svg-icons/faBluetoothB'
import { faDocker } from '@fortawesome/free-brands-svg-icons/faDocker'
import { faGit } from '@fortawesome/free-brands-svg-icons/faGit'
import { faGithub } from '@fortawesome/free-brands-svg-icons/faGithub'
import { faGoogle } from '@fortawesome/free-brands-svg-icons/faGoogle'
import { faGooglePlay } from '@fortawesome/free-brands-svg-icons/faGooglePlay'
import { faLinux } from '@fortawesome/free-brands-svg-icons/faLinux'
import { faMedium } from '@fortawesome/free-brands-svg-icons/faMedium'
import { faOpenid } from '@fortawesome/free-brands-svg-icons/faOpenid'
import { faRaspberryPi } from '@fortawesome/free-brands-svg-icons/faRaspberrypi'
import { faReact } from '@fortawesome/free-brands-svg-icons/faReact'
import { faUbuntu } from '@fortawesome/free-brands-svg-icons/faUbuntu'
import { faUsb } from '@fortawesome/free-brands-svg-icons/faUsb'
import { faWindows } from '@fortawesome/free-brands-svg-icons/faWindows'

export const fab = { faAndroid, faApple, faAws, faBluetooth, faBluetoothB, faDocker, faGit, faGithub, faGoogle, faGooglePlay, faLinux, faMedium, faOpenid, faRaspberryPi, faReact, faUbuntu, faUsb, faWindows }
export default { fab }
