#!/bin/sh
cd ~/../../usr/local/bin/;
curl -O https://downloads.remote.it/cli/v1.5.5/remoteit_mac-osx_x86_64;
mv remoteit_mac-osx_x86_64 remoteit;
chmod 755 remoteit;
./remoteit -j tools install --update;
./remoteit -j service uninstall;
./remoteit -j service install;
# message to console of osx
syslog -s -l error "remot3it says: services installed successfully!"
exit 0