// The platform catalogue: a build-time snapshot of the API's platformTypes / platformInstallations
// (graphql-api docs/PLATFORM-CATALOGUE.md), regenerated by scripts/platforms-generate.mjs and
// committed. The app reads only this file — there is no runtime fetch — so a catalogue change
// reaches clients when the snapshot is regenerated and shipped. The desktop keeps only what is
// code (logo components, one override, a few JSX blocks) in platforms/<id>/index.tsx.
import raw from './catalogue.generated.json'

export type CatalogueKind = 'command' | 'code' | 'download' | 'info'

export interface CatalogueType {
  name: string
  displayName?: string
}

export interface CatalogueInstallation {
  name: string
  kind: CatalogueKind
  // Present only on the few rows the API renders with their own template (Docker, IDY). The
  // registry substitutes [CODE] client-side for these — identical to the API's output once a
  // stage renders server-side — so the command is right regardless of deploy order.
  commandTemplate?: string
  qualifier?: string
  instructions?: string
  link?: string
  altLink?: string
  // [] = no default service (Docker); absent = unspecified, the UI's default applies.
  services?: IServiceRegistration[]
  // Platform type ids this page onboards, with their labels.
  types: Record<string, string>
}

export interface Catalogue {
  types: Record<string, CatalogueType>
  installations: Record<string, CatalogueInstallation>
}

export const CATALOGUE = raw as Catalogue
