// GENERATED by scripts/platforms-generate.mjs — do not edit. CI fails when this is stale.
// Source of truth: the GraphQL API's platformTypes catalogue (graphql-api docs/PLATFORM-CATALOGUE.md).
// Regenerate: npm run platforms:generate    Verify: npm run platforms:check

export type CatalogueKind = 'command' | 'code' | 'download' | 'info'

export interface CatalogueType {
  name: string
  displayName?: string
  installation?: string // slug into installations
}

export interface CatalogueInstallation {
  name: string
  kind: CatalogueKind
  commandTemplate?: string
  qualifier?: string
  instructions?: string
  link?: string
  altLink?: string
  services?: { application: number; port?: number }[]
}

export const CATALOGUE: { types: Record<string, CatalogueType>; installations: Record<string, CatalogueInstallation> } = {
  "types": {
    "0": {
      "name": "Windows",
      "installation": "windows"
    },
    "4": {
      "name": "Windows"
    },
    "5": {
      "name": "Windows Desktop",
      "installation": "windows"
    },
    "10": {
      "name": "Windows Server",
      "installation": "windows"
    },
    "256": {
      "name": "Mac",
      "installation": "mac"
    },
    "407": {
      "name": "Lorex DVR 1"
    },
    "408": {
      "name": "Lorex DVR 2"
    },
    "768": {
      "name": "Generic Unix"
    },
    "769": {
      "name": "Generic Linux",
      "displayName": "Linux",
      "installation": "linux"
    },
    "1024": {
      "name": "Drobo Box"
    },
    "1025": {
      "name": "Lorex Zavio Web"
    },
    "1026": {
      "name": "Lorex Zavio Streamer"
    },
    "1030": {
      "name": "Astak Mole"
    },
    "1033": {
      "name": "Pixord"
    },
    "1040": {
      "name": "Lorex DVR 1"
    },
    "1041": {
      "name": "Lorex NVR"
    },
    "1042": {
      "name": "Lorex DVR 2"
    },
    "1043": {
      "name": "Cisco NAS 1"
    },
    "1053": {
      "name": "Cisco NAS 2"
    },
    "1054": {
      "name": "Cisco NAS 3"
    },
    "1056": {
      "name": "Stem"
    },
    "1057": {
      "name": "Philips M100"
    },
    "1058": {
      "name": "Philips B100"
    },
    "1059": {
      "name": "Philips B120"
    },
    "1060": {
      "name": "Astak Mini Mole"
    },
    "1062": {
      "name": "Foscam"
    },
    "1063": {
      "name": "Amnimo",
      "installation": "amnimo"
    },
    "1072": {
      "name": "Raspberry Pi",
      "installation": "raspberrypi"
    },
    "1075": {
      "name": "remote.it Pi",
      "displayName": "Remote.It Pi",
      "installation": "raspberrypi"
    },
    "1076": {
      "name": "remote.it Pi Lite",
      "displayName": "Remote.It Pi Lite",
      "installation": "raspberrypi"
    },
    "1077": {
      "name": "remote.it Pi 64",
      "displayName": "Remote.It Pi 64",
      "installation": "raspberrypi"
    },
    "1120": {
      "name": "Debian Linux",
      "installation": "ubuntu"
    },
    "1121": {
      "name": "RedHat Linux",
      "installation": "linux"
    },
    "1122": {
      "name": "Alpine Linux",
      "installation": "alpine"
    },
    "1185": {
      "name": "AWS Cloud",
      "displayName": "AWS",
      "installation": "aws"
    },
    "1186": {
      "name": "Azure Cloud",
      "displayName": "Azure",
      "installation": "azure"
    },
    "1187": {
      "name": "Google Cloud",
      "installation": "gcp"
    },
    "1200": {
      "name": "ARM Linux",
      "displayName": "Linux ARM",
      "installation": "linux"
    },
    "1201": {
      "name": "NVIDIA Jetson",
      "installation": "nvidia"
    },
    "1202": {
      "name": "x86 Generic Linux"
    },
    "1204": {
      "name": "Netcom NWL25"
    },
    "1205": {
      "name": "OpenWrt",
      "installation": "openwrt"
    },
    "1206": {
      "name": "Advantech",
      "installation": "advantech"
    },
    "1207": {
      "name": "Furukawa"
    },
    "1208": {
      "name": "Dragino"
    },
    "1209": {
      "name": "AXIS",
      "installation": "axis"
    },
    "1210": {
      "name": "Synology",
      "installation": "nas"
    },
    "1211": {
      "name": "TEKTELIC"
    },
    "1212": {
      "name": "NETGEAR"
    },
    "1213": {
      "name": "Android",
      "displayName": "Android Phone",
      "installation": "android"
    },
    "1214": {
      "name": "iOS",
      "displayName": "iPhone",
      "installation": "ios"
    },
    "1215": {
      "name": "ASUS",
      "displayName": "ASUS Tinker Board",
      "installation": "tinkerboard"
    },
    "1216": {
      "name": "Firewalla",
      "installation": "firewalla"
    },
    "1217": {
      "name": "AVH Cloud",
      "displayName": "AVH",
      "installation": "arm"
    },
    "1218": {
      "name": "Ubiquiti",
      "displayName": "Ubiquiti Router",
      "installation": "ubiquiti"
    },
    "1219": {
      "name": "Docker",
      "displayName": "Docker Container",
      "installation": "docker"
    },
    "1220": {
      "name": "Docker Extension",
      "installation": "docker-extension"
    },
    "1221": {
      "name": "Docker Jumpbox",
      "installation": "docker-jumpbox"
    },
    "1222": {
      "name": "Demo Device"
    },
    "1223": {
      "name": "Embedded Works Jumpbox",
      "displayName": "Embedded Works",
      "installation": "embedded-works"
    },
    "1224": {
      "name": "Cachengo Host",
      "displayName": "Cachengo",
      "installation": "cachengo"
    },
    "1225": {
      "name": "IDY",
      "installation": "idy"
    },
    "1226": {
      "name": "Liverock",
      "displayName": "Liverock Technologies",
      "installation": "liverock"
    },
    "1227": {
      "name": "Cachengo RaN",
      "displayName": "Rent-A-Node",
      "installation": "cachengo"
    },
    "1228": {
      "name": "TOA",
      "installation": "toa"
    },
    "1280": {
      "name": "Unknown"
    },
    "1281": {
      "name": "Teltonika",
      "installation": "teltonika"
    },
    "9999": {
      "name": "Legacy Camera"
    },
    "65535": {
      "name": "Unknown",
      "installation": "unknown"
    },
    "65536": {
      "name": "Any"
    }
  },
  "installations": {
    "windows": {
      "name": "Windows",
      "kind": "download",
      "qualifier": "Windows installation",
      "instructions": "Install the Desktop or CLI on the Windows system to you want to enable remote access to.",
      "link": "https://link.remote.it/download/desktop"
    },
    "mac": {
      "name": "Mac",
      "kind": "download",
      "qualifier": "Macintosh installation",
      "instructions": "Install the Desktop or CLI on the Mac to you want to enable remote access to.",
      "link": "https://link.remote.it/download/desktop"
    },
    "linux": {
      "name": "Linux",
      "kind": "command",
      "qualifier": "For any Linux based system",
      "link": "https://link.remote.it/support/streamline-install",
      "altLink": "https://link.remote.it/docs/oem-overview"
    },
    "amnimo": {
      "name": "Amnimo",
      "kind": "info"
    },
    "raspberrypi": {
      "name": "Raspberry Pi",
      "kind": "command",
      "qualifier": "For any Raspberry Pi or Linux based system",
      "link": "https://link.remote.it/support/streamline-install",
      "altLink": "https://link.remote.it/docs/oem-overview"
    },
    "ubuntu": {
      "name": "Ubuntu Desktop",
      "kind": "download",
      "qualifier": "For Ubuntu Desktop systems",
      "link": "https://link.remote.it/download/desktop"
    },
    "alpine": {
      "name": "Alpine Linux",
      "kind": "command",
      "qualifier": "For Alpine Linux based systems",
      "link": "https://link.remote.it/support/streamline-install"
    },
    "aws": {
      "name": "AWS",
      "kind": "command",
      "qualifier": "For any Linux based AWS virtual machine",
      "link": "https://link.remote.it/support/streamline-install"
    },
    "azure": {
      "name": "Azure",
      "kind": "command",
      "qualifier": "For any Linux based Azure Cloud virtual machine",
      "link": "https://link.remote.it/support/streamline-install"
    },
    "gcp": {
      "name": "Google Cloud",
      "kind": "command",
      "qualifier": "For any Linux based Google Cloud instance",
      "link": "https://link.remote.it/support/streamline-install"
    },
    "nvidia": {
      "name": "NVIDIA Jetson",
      "kind": "command",
      "qualifier": "For NVIDIA Jetson systems",
      "link": "https://link.remote.it/support/streamline-install"
    },
    "openwrt": {
      "name": "OpenWrt",
      "kind": "command",
      "qualifier": "For OpenWrt routers",
      "link": "https://link.remote.it/support/streamline-install"
    },
    "advantech": {
      "name": "Advantech",
      "kind": "command",
      "qualifier": "For Advantech systems",
      "link": "https://link.remote.it/support/streamline-install"
    },
    "axis": {
      "name": "AXIS",
      "kind": "command",
      "qualifier": "For AXIS camera systems",
      "link": "https://link.remote.it/support/streamline-install"
    },
    "nas": {
      "name": "Synology",
      "kind": "download",
      "qualifier": "Synology manual installation",
      "instructions": "Download the package file and install it through your NAS web interface.",
      "link": "https://link.remote.it/getting-started/synology"
    },
    "android": {
      "name": "Android",
      "kind": "code",
      "qualifier": "To register an Android phone or tablet",
      "link": "https://play.google.com/store/apps/details?id=it.remote.screenview",
      "services": [
        {
          "application": 48
        }
      ]
    },
    "ios": {
      "name": "iOS",
      "kind": "info"
    },
    "tinkerboard": {
      "name": "Tinker Board",
      "kind": "command",
      "qualifier": "For the ASUS Tinker Board",
      "link": "https://link.remote.it/support/streamline-install"
    },
    "firewalla": {
      "name": "Firewalla",
      "kind": "command",
      "qualifier": "For any Firewalla system",
      "link": "https://link.remote.it/support/streamline-install"
    },
    "arm": {
      "name": "Arm Virtual Hardware",
      "kind": "command",
      "qualifier": "For the Arm Virtual Hardware platform",
      "link": "https://link.remote.it/avh"
    },
    "ubiquiti": {
      "name": "Ubiquiti",
      "kind": "command",
      "qualifier": "For Ubiquiti routers",
      "link": "https://link.remote.it/support/streamline-install"
    },
    "docker": {
      "name": "Docker",
      "kind": "command",
      "commandTemplate": "docker run -d -e R3_REGISTRATION_CODE=\"[CODE]\" --restart unless-stopped --pull always remoteit/remoteit-agent:latest",
      "qualifier": "For testing on any system running Docker",
      "link": "https://hub.docker.com/r/remoteit/remoteit-agent"
    },
    "docker-extension": {
      "name": "Docker Jumpbox Extension",
      "kind": "code",
      "qualifier": "For docker desktop"
    },
    "docker-jumpbox": {
      "name": "Docker Jumpbox",
      "kind": "command",
      "commandTemplate": "docker run -d  -e R3_REGISTRATION_CODE=\"[CODE]\"  -v /var/run/docker.sock:/var/run/docker.sock  --restart unless-stopped  --name remoteit_docker_jumpbox  --pull always  remoteit/docker-extension:latest",
      "qualifier": "For testing on any system running Docker",
      "link": "https://hub.docker.com/r/remoteit/docker-extension"
    },
    "embedded-works": {
      "name": "Embedded Works",
      "kind": "info"
    },
    "cachengo": {
      "name": "Cachengo",
      "kind": "command"
    },
    "idy": {
      "name": "IDY",
      "kind": "command",
      "commandTemplate": "config net-remoteit-agent=enable; config net-remoteit-registration_code=[CODE]; /etc/init.d/remoteit-refresh start",
      "qualifier": "For IDY routers and gateways",
      "link": "https://link.remote.it/support/streamline-install"
    },
    "liverock": {
      "name": "Liverock Technologies",
      "kind": "info"
    },
    "toa": {
      "name": "TOA",
      "kind": "info"
    },
    "teltonika": {
      "name": "Teltonika",
      "kind": "command",
      "qualifier": "For Teltonika routers and gateways",
      "link": "https://link.remote.it/support/streamline-install"
    },
    "unknown": {
      "name": "Unknown",
      "kind": "code",
      "qualifier": "For generic device registration",
      "instructions": "This unique code allows any device to register with your account, keep it safe."
    }
  }
}
