// The platform catalogue: a build-time snapshot of the API's platformTypes / platformInstallations
// (graphql-api docs/PLATFORM-CATALOGUE.md), regenerated by scripts/platforms-generate.mjs and
// committed. The app reads only this file — there is no runtime fetch — so a catalogue change
// reaches clients when the snapshot is regenerated and shipped. The desktop keeps only what is
// code (logo components, one override, a few JSX blocks) in platforms/<id>/index.tsx.
import raw from './catalogue.generated.json'

export type CatalogueKind = 'command' | 'code' | 'download' | 'info'

export interface CatalogueInstallation {
  name: string
  kind: CatalogueKind
  // Present only on the few rows the API renders with their own template (Docker, IDY). The
  // registry substitutes [CODE] client-side for these — identical to the API's output once a
  // stage renders server-side — so the command is right regardless of deploy order.
  commandTemplate?: string
  // A complete sentence saying who the page is for. The client adds its own action line.
  description?: string
  instructions?: string
  // Where the platform is installed from (download, app store, docs article).
  link?: string
  // [] = no default service (Docker); absent = unspecified, the UI's default applies.
  services?: IServiceRegistration[]
  // Platform type ids this page onboards, with their labels.
  types: Record<string, string>
}

export interface Catalogue {
  // Platform type id to the name to show for it (the API's `label`: displayName, else name).
  types: Record<string, string>
  // Types that more than one page onboards, default first (the API's sortOrder). A type absent
  // here has exactly one page: the one whose `types` lists it.
  routes: Record<string, string[]>
  installations: Record<string, CatalogueInstallation>
}

export const CATALOGUE = raw as Catalogue
