name: Trigger Cachengo Build

on:
  push:
    branches:
      - cachengo

# This ensures the workflow only runs meaningful jobs in the remoteit/desktop repository
jobs:
  check_repository:
    runs-on: ubuntu-latest
    outputs:
      should_run: ${{ github.repository == 'remoteit/desktop' }}
    steps:
      - name: Check repository
        run: |
          echo "Running in repository: ${{ github.repository }}"
          echo "Should continue: ${{ github.repository == 'remoteit/desktop' }}"

  dispatch:
    needs: check_repository
    if: needs.check_repository.outputs.should_run == 'true'
    runs-on: ubuntu-latest
    steps:
      - name: Dispatch to cachengo/desktop
        run: |
          curl -X POST \
            -H "Accept: application/vnd.github.v3+json" \
            -H "Authorization: Bearer ${{ secrets.DISPATCH_TOKEN }}" \
            https://api.github.com/repos/cachengo/desktop/dispatches \
            -d '{"event_type": "sync-from-remoteit"}'