name: Trigger Cachengo Build

on:
  push:
    branches:
      - cachengo

jobs:
  debug:
    runs-on: ubuntu-latest
    steps:
      - name: Print repository name
        run: echo "Current repository is ${{ github.repository }}"

  dispatch:
    runs-on: ubuntu-latest
    needs: debug
    # Skip this job if running in the cachengo/desktop repository
    if: github.repository == 'remoteit/desktop'
    steps:
      - name: Dispatch to cachengo/desktop
        run: |
          curl -X POST \
            -H "Accept: application/vnd.github.v3+json" \
            -H "Authorization: Bearer ${{ secrets.DISPATCH_TOKEN }}" \
            https://api.github.com/repos/cachengo/desktop/dispatches \
            -d '{"event_type": "sync-from-remoteit"}'