name: Build/release-s3

on: 
  workflow_dispatch:
    inputs:
      tag:
        description: 'Version tag (ex: v1.0.0)'     
        required: true
        default: 'warning'
      s3_path:
        description: 'S3 path (ex: test/desktop/)'     
        required: true
        default: 'deskop/'
defaults:
  run:
    shell: bash

jobs:

  release-s3:
    runs-on: ubuntu-latest
    steps:
      - name: Download release assets to workspace
        uses: robinraju/release-downloader@v1.8
        with: 
          # A flag to set the download target as latest release
          # The default value is 'false'
          # latest: true
          
          # The github tag. e.g: v1.0.1
          # Download assets from a specific tag/version
          tag: "${{ github.event.inputs.tag }}"
          
          # Relative path under $GITHUB_WORKSPACE to place the downloaded file(s)
          # It will create the target directory automatically if not present
          # eg: out-file-path: "my-downloads" => It will create directory $GITHUB_WORKSPACE/my-downloads
          out-file-path: "release-assets"
      
          # A flag to set if the downloaded assets are archives and should be extracted
          # Checks all downloaded files if they end with zip, tar or tar.gz and extracts them, if true.
          # Prints a warning if enabled but file is not an archive - but does not fail.
          extract: false
      
      - name: Upload release assets to S3
        uses: shallwefootball/s3-upload-action@master
        with:
          source_dir: 'release-assets'
          aws_key_id: ${{ secrets.AWS_KEY_ID }}
          aws_secret_access_key: ${{ secrets.AWS_SECRET_ACCESS_KEY}}
          aws_bucket: ${{ secrets.AWS_BUCKET }}
          destination_dir: ${{ github.event.inputs.s3_path }}/${{ github.event.inputs.tag }}/
